### ISSUE TITLE
Improve documentation of fitsio.Close

### ISSUE THREAD

**Issue by airnandez** [astrogo/fitsio#32]
Documentation of [`fitsio.Close()`](https://github.com/astrogo/fitsio/blob/master/file.go#L106) should state that if the `io.Reader` passed as argument to `fitsio.Open` implements `io.Closer` then the `Close()` method of the reader will be automatically called.

**Comment by sbinet** [comment]
right... it does that...

actually, I am not completely sure it should close the underlying `io.Reader`.
it kind of breaks the usual Go idiom (the `bufio.NewReader` doesn't do that, for example).

I wrote it like that because I was still with a python/C++ mindset.
I'd be inclined to remove that piece of code. what do you think?

**Comment by airnandez** [comment]
In my opinion, since `fitsio.Open` does not actually open the underlying file, `fitsio.Close` should not close it. `fitsio.Close` should release all the resources acquired by `fitsio.Open` only.

**Comment by airnandez** [comment]
Thank you !
